/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.ishadi;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import time_table_management_system.DBConnect;

/**
 *
 * @author ishadi
 */
public class dashboard extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement load = null;
    ResultSet rs = null;
    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        con = DBConnect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(new java.awt.Color(51, 51, 255));

        jPanel1.setBackground(new java.awt.Color(189, 189, 189));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 52)); // NOI18N
        jLabel1.setText("Locations");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("ADD LOCATION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("DASHBOARD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton4.setText("CONSECUTIVE  LOCATION");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton5.setText("MANAGE LOCATION");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton6.setText("SESSION LOCATION");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(476, 476, 476)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jButton5)
                                .addGap(75, 75, 75)
                                .addComponent(jButton4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jButton6)))))
                .addGap(117, 117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(273, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        addlocation L1 = new addlocation();
        L1.setVisible(true);
        this.dispose();
        
     
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
  
          try{
        statistics  s1 = new statistics  ();
        
        String count6= "SELECT count(subj_code)from subject WHERE offered_year=1";
        load = con.prepareStatement(count6);
        rs= load.executeQuery();
        if(rs.next()){
            
            String count1_sub = rs.getString("count(subj_code)");
            
        }
         String count7= "SELECT count(subj_code)from subject WHERE offered_year=2";
        load = con.prepareStatement(count7);
        rs= load.executeQuery();
        if(rs.next()){
            
            String count2_sub = rs.getString("count(subj_code)");
            
        }
        
        String count8= "SELECT count(subj_code)from subject WHERE offered_year=3";
        load = con.prepareStatement(count8);
        rs= load.executeQuery();
        if(rs.next()){
            
            String count3_sub = rs.getString("count(subj_code)");
            
        }
         String count9= "SELECT count(subj_code)from subject WHERE offered_year=4";
        load = con.prepareStatement(count9);
        rs= load.executeQuery();
        if(rs.next()){
            
            String count4_sub = rs.getString("count(subj_code)");
            
        }
        
        
        
        
        
        
        
        
        
        
        
        
        //Count
        String count1= "SELECT count(lectur_name)from lecturer ";
        load = con.prepareStatement(count1);
        rs= load.executeQuery();
        if(rs.next()){
            
            String count_lec = rs.getString("count(lectur_name)");
            statistics.lecbox.setText(count_lec);
        }
        
      
        //Count
        String count2= "SELECT count(subj_code)from subject  ";
        load = con.prepareStatement(count2);
        rs= load.executeQuery();
        if(rs.next()){
            
            String count_sub = rs.getString("count(subj_code)");
            statistics.stubox.setText(count_sub);
        }
        
        //Count
        String count3= "SELECT count(ID)from studentgroup  ";
        load = con.prepareStatement(count3);
        rs= load.executeQuery();
        if(rs.next()){
            
            String count_grp = rs.getString("count(ID)");
            statistics.grpbox.setText(count_grp);
        }
        
         //Count
        String count4= "SELECT count(roomName)from location  ";
        load = con.prepareStatement(count4);
        rs= load.executeQuery();
        if(rs.next()){
            
            String count_loc = rs.getString("count(roomName)");
            statistics.locationBox.setText(count_loc);
        }
        
        
        //What's new
        
        String sql = "SELECT lectur_name  FROM lecturer ORDER BY  eid DESC LIMIT 0,1";
        load = con.prepareStatement(sql);
        rs= load.executeQuery(sql);
        
        while(rs.next()){
              String name = rs.getString("lectur_name");
              statistics.lecturerbox.setText(name);
       
        }
         s1.setVisible(true);
        this.dispose();
        
        String sq1 = "SELECT subj_name FROM subject ORDER BY  subj_code DESC LIMIT 0,1";
        load = con.prepareStatement(sq1);
        rs= load.executeQuery(sq1);
        
        while(rs.next()){
            String sname = rs.getString("subj_name");
            statistics.subBox.setText(sname);
       
        }
         s1.setVisible(true);
        this.dispose();
        
        String sq2 = "SELECT roomName FROM location ORDER BY roomID DESC LIMIT 0,1";
        load = con.prepareStatement(sq2);
        rs= load.executeQuery(sq2);
        
        while(rs.next()){
            String rname = rs.getString("roomName");
            statistics.LocaBox.setText(rname);
       
        }
         s1.setVisible(true);
        this.dispose();
        
        String sq3 = "SELECT GroupId FROM studentgroup ORDER BY ID DESC LIMIT 0,1";
        load = con.prepareStatement(sq3);
        rs= load.executeQuery(sq3);
        
        while(rs.next()){
            String gname = rs.getString("GroupId");
            statistics.grpBox.setText(gname);
       
        }
         s1.setVisible(true);
        this.dispose();
        
        
        //bar chart
        
       
         }catch(Exception e){
             
         }
        
       
                                   
       
        
             
        
        
        
      
               
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        consecutiveSession c1 = new consecutiveSession ();
        c1.setVisible(true);
        this.dispose();
        
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        manageLocation M1 = new manageLocation ();
        M1.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        manageSessionRoom S1 = new manageSessionRoom ();
        S1.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
